### ISSUE TITLE
Poor performance in the new MacBook Pro 2016

### ISSUE THREAD

**Issue by tigredicarta** [radiant-player/radiant-player-mac#626]
The application is unusable due to slowness in scroll and a lot of reloads.
The same problem does not occur on a MacBook Air.

System: OS X 10.12.1 (Sierra)
App: 1.11.2

**Comment by mrosenfield** [comment]
Having the same issues on my 2016 MacBook pro!

**Comment by swanitzek** [comment]
I don't have any performance issues with my MacBook Pro 2016 (15 inch).

**Comment by tigredicarta** [comment]
Yes, from the very first start of the application. In these conditions it is unfortunately unusable.

**Comment by jacobwgillespie** [comment]
Are all of you experiencing issues using the 13" MBPt?

Separately, can you try running https://dl.dropboxusercontent.com/u/6278910/Radiant%20Player-2.0.0-alpha-2.dmg to see if you experience the same performance issues?  It's a very early build of the new Radiant v2, and while it doesn't really have many features, I'm curious to see how the performance holds up.

**Comment by mrosenfield** [comment]
I am experiencing it on the 15 inch w/ TB.

Will try the new build tonight! Thanks.

**Comment by tigredicarta** [comment]
The alpha build works perfectly.
I'm waiting for the final release with all the features :)

**Comment by jacobwgillespie** [comment]
Sweet!  I'm hoping to find some free time to get the rest of the features ported over soon...

**Comment by MattyKuzyk** [comment]
👍 to this. Close to unusable on my 15 inch MBP 2016.

**Comment by jbourassa** [comment]
I tried the beta on my MBP 13' w/ TouchBar but ran into this when trying to play a record from the launch/home screen, I figured I should share.

```
Uncaught Exception:
TypeError: Cannot read property 'webContents' of null
    at send (/Applications/Radiant Player 2 alpha.app/Contents/Resources/app/backend.js:811:40)
    at Object.emit (/Applications/Radiant Player 2 alpha.app/Contents/Resources/app/backend.js:213:13)
    at EventEmitter.<anonymous> (/Applications/Radiant Player 2 alpha.app/Contents/Resources/app/backend.js:850:26)
    at emitTwo (events.js:106:13)
    at EventEmitter.emit (events.js:191:7)
    at /Applications/Radiant Player 2 alpha.app/Contents/Resources/app/node_modules/osx-mouse/index.js:11:9
```

At any rate, I'm looking forward to using this new version. Thanks for working on this project, it really makes Google Play Music a lot more enjoyable.
